stages:
  - build
  - docs

build_release:
  image: rustlang/rust:nightly
  stage: build
  script: 
    - cargo build --release
  artifacts:
    paths:
      - target/release/bio_algos
    expire_in: 1yr

pages:
  image: rustlang/rust:nightly
  stage: docs
  script:
    - cargo doc --no-deps
    - mkdir public
    - cp -r target/doc/* public
  artifacts:
    paths:
    - public
  only:
  - master
