stages:
  - test
  - build
  - assignment
  - docs

run_tests:
  image: rustlang/rust:nightly
  stage: test
  script:
    - cargo test

build_release:
  image: rustlang/rust:nightly
  stage: build
  script: 
    - cargo build --release
  artifacts:
    paths:
      - target/release/bio_algos
    expire_in: 1yr

build_assignment:
  image: jupyter/datascience-notebook
  stage: assignment
  script:
    - cp target/release/bio_algos pwm-assignment
    - cd pwm-assignment 
    - jupyter nbconvert --ExecutePreprocessor.kernel_name=python3 --output=protocol --execute pwm-assignment.ipynb 
    - cd ..
    - tar -czvf hundt_robin.tar.gz *
  artifacts:
    paths:
      - hundt_robin.tar.gz
    expire_in: 1yr

pages:
  image: rustlang/rust:nightly
  stage: docs
  script:
    - cargo doc --no-deps
    - mkdir public
    - cp -r target/doc/* public
  artifacts:
    paths:
    - public
    expire_in: 1yr
  only:
  - master
