[package]
name = "bio_algos"
version = "0.1.0"
authors = ["robinwilliam.hundt <robinwilliam.hundt@stud.uni-goettingen.de>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
ndarray = {version = "0.12.0", features = ["serde-1"]}
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.33"

